services:
  magiclists:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magiclists
    ports:
      - "4545:8000"
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app/data/magiclists.db
    volumes:
      - magiclists_data:/app/data
    restart: unless-stopped
volumes:
  magiclists_data:
    driver: local