services:
  magiclists:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magiclists
    ports:
      - "4545:8000"
    env_file:
      - .env
    volumes:
      - magiclists_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  magiclists_data:
    driver: local